const shopActionTypes = {
    FETCH_COLLLECTION_START: "FETCH_COLLLECTION_START",
    FETCH_COLLLECTION_FAILURE: "FETCH_COLLLECTION_FAILURE",
    FETCH_COLLLECTION_SUCCESS: "FETCH_COLLLECTION_SUCCESS"
};

export default shopActionTypes;
